typography_spectrum: 0.72012
color:
  brandColors:
    - '#e5c87c'
    - '#1a1511'
    - '#5e380b'
    - '#c39e34'
    - '#905b15'
  brandStrength: 0.5625
  lightness: 0.5625
  saturation: 0.4375
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/8540bd32-0c75-4775-87f5-38c2a0577a31.jpg
name: Daniel Murray Art
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Daniel Murray Artist - Official webpage
description: Visual artist working in the Highlands
purpose: []
