name: Daniel Murray Art
favicon: null
layout_spectrum: 0.6145075710956007
typography_spectrum: 0.06509994831867516
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.6339110191911459
  lightness: 0.19746304699219763
  saturation: 0.1574041503481567
  rhythmicContrast: 0.12309930380433798
purpose: []
