name: Daniel Murray Art
favicon: null
layout_spectrum: 1
typography_spectrum: 0.72012
title: Official webpage
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e5c87c'
    - '#1a1511'
    - '#5e380b'
    - '#c39e34'
    - '#905b15'
  brandStrength: 0.5625
  lightness: 0.5625
  saturation: 0.4375
  rhythmicContrast: 0.5
purpose: []
